# Supported funding model platforms

github: [s0fractal]
patreon: s0fractal
# open_collective: s0fractal
ko_fi: s0fractal
# tidelift:
# community_bridge:
# liberapay:
# issuehunt:
# lfx_crowdfunding:
# polar:
# buy_me_a_coffee:
# thanks_dev:
# custom:
